//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emloyee.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalary
    {
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public string Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
